version: '3.7'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    container_name: skato_server
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    env_file: ./backend/.env
    links:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - skato-network


  db:
    container_name: my_database_server
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    networks:
    - skato-network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
    - skato-network

networks:
  skato-network:
    driver: bridge