FROM node:lts-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app


# Install Dependencies
COPY package.json .
COPY package-lock.json .

RUN npm install

# Copy app source code
COPY . .

# Exports
EXPOSE 8000

# Run npm start script with PM2 when container starts
CMD [ "npm",  "run", "start:dev"]